package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsBanner;
import com.fly.twosoft.dao.twosoft.single.model.TsBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int countByExample(TsBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int deleteByExample(TsBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int insert(TsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int insertSelective(TsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    List<TsBanner> selectByExample(TsBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    TsBanner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsBanner record, @Param("example") TsBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsBanner record, @Param("example") TsBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_BANNER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsBanner record);
}