package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsDataChange;
import com.fly.twosoft.dao.twosoft.single.model.TsDataChangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsDataChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int countByExample(TsDataChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int deleteByExample(TsDataChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int insert(TsDataChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int insertSelective(TsDataChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    List<TsDataChange> selectByExample(TsDataChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    TsDataChange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsDataChange record, @Param("example") TsDataChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsDataChange record, @Param("example") TsDataChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsDataChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DATA_CHANGE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsDataChange record);
}