package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsDict;
import com.fly.twosoft.dao.twosoft.single.model.TsDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int countByExample(TsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int deleteByExample(TsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String dictKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int insert(TsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int insertSelective(TsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    List<TsDict> selectByExample(TsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    TsDict selectByPrimaryKey(String dictKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsDict record, @Param("example") TsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsDict record, @Param("example") TsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsDict record);
}