package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseShareholderHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseShareholderHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseShareholderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseShareholderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseShareholderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseShareholderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseShareholderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    List<TsEnterpriseShareholderHistory> selectByExample(TsEnterpriseShareholderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    TsEnterpriseShareholderHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseShareholderHistory record, @Param("example") TsEnterpriseShareholderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseShareholderHistory record, @Param("example") TsEnterpriseShareholderHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseShareholderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseShareholderHistory record);
}