package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseLog;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    List<TsEnterpriseLog> selectByExample(TsEnterpriseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    TsEnterpriseLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseLog record, @Param("example") TsEnterpriseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseLog record, @Param("example") TsEnterpriseLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseLog record);
}