package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseShareholder;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseShareholderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseShareholderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    List<TsEnterpriseShareholder> selectByExample(TsEnterpriseShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    TsEnterpriseShareholder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseShareholder record, @Param("example") TsEnterpriseShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseShareholder record, @Param("example") TsEnterpriseShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseShareholder record);
}