package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseHardware;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseHardwareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseHardwareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    List<TsEnterpriseHardware> selectByExample(TsEnterpriseHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    TsEnterpriseHardware selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseHardware record, @Param("example") TsEnterpriseHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseHardware record, @Param("example") TsEnterpriseHardwareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseHardware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseHardware record);
}