package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseVerify;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseVerifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseVerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    List<TsEnterpriseVerify> selectByExample(TsEnterpriseVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    TsEnterpriseVerify selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseVerify record, @Param("example") TsEnterpriseVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseVerify record, @Param("example") TsEnterpriseVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_VERIFY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseVerify record);
}