package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseStaffStock;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseStaffStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseStaffStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseStaffStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseStaffStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseStaffStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseStaffStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    List<TsEnterpriseStaffStock> selectByExample(TsEnterpriseStaffStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    TsEnterpriseStaffStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseStaffStock record, @Param("example") TsEnterpriseStaffStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseStaffStock record, @Param("example") TsEnterpriseStaffStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseStaffStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseStaffStock record);
}