package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseHardwareHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseHardwareHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseHardwareHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseHardwareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseHardwareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseHardwareHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseHardwareHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    List<TsEnterpriseHardwareHistory> selectByExample(TsEnterpriseHardwareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    TsEnterpriseHardwareHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseHardwareHistory record, @Param("example") TsEnterpriseHardwareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseHardwareHistory record, @Param("example") TsEnterpriseHardwareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseHardwareHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_HARDWARE_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseHardwareHistory record);
}