package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseProduct;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    List<TsEnterpriseProduct> selectByExample(TsEnterpriseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    TsEnterpriseProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseProduct record, @Param("example") TsEnterpriseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseProduct record, @Param("example") TsEnterpriseProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseProduct record);
}