package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseSoftHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseSoftHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseSoftHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseSoftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseSoftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseSoftHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseSoftHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    List<TsEnterpriseSoftHistory> selectByExample(TsEnterpriseSoftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    TsEnterpriseSoftHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseSoftHistory record, @Param("example") TsEnterpriseSoftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseSoftHistory record, @Param("example") TsEnterpriseSoftHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseSoftHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseSoftHistory record);
}