package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterprisePrint;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterprisePrintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterprisePrintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int countByExample(TsEnterprisePrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterprisePrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int insert(TsEnterprisePrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterprisePrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    List<TsEnterprisePrint> selectByExample(TsEnterprisePrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    TsEnterprisePrint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterprisePrint record, @Param("example") TsEnterprisePrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterprisePrint record, @Param("example") TsEnterprisePrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterprisePrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterprisePrint record);
}