package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseBusinessHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseBusinessHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseBusinessHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseBusinessHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseBusinessHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseBusinessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseBusinessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    List<TsEnterpriseBusinessHistory> selectByExample(TsEnterpriseBusinessHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    TsEnterpriseBusinessHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseBusinessHistory record, @Param("example") TsEnterpriseBusinessHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseBusinessHistory record, @Param("example") TsEnterpriseBusinessHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseBusinessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseBusinessHistory record);
}