package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseProductHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseProductHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseProductHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    List<TsEnterpriseProductHistory> selectByExample(TsEnterpriseProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseProductHistory record, @Param("example") TsEnterpriseProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseProductHistory record, @Param("example") TsEnterpriseProductHistoryExample example);
}