package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseBusiness;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseBusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    List<TsEnterpriseBusiness> selectByExample(TsEnterpriseBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    TsEnterpriseBusiness selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseBusiness record, @Param("example") TsEnterpriseBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseBusiness record, @Param("example") TsEnterpriseBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseBusiness record);
}