package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseStaffStockHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseStaffStockHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseStaffStockHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseStaffStockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseStaffStockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseStaffStockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseStaffStockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    List<TsEnterpriseStaffStockHistory> selectByExample(TsEnterpriseStaffStockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    TsEnterpriseStaffStockHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseStaffStockHistory record, @Param("example") TsEnterpriseStaffStockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseStaffStockHistory record, @Param("example") TsEnterpriseStaffStockHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseStaffStockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_STAFF_STOCK_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseStaffStockHistory record);
}