package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseSoft;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseSoftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseSoftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    List<TsEnterpriseSoft> selectByExample(TsEnterpriseSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    TsEnterpriseSoft selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseSoft record, @Param("example") TsEnterpriseSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseSoft record, @Param("example") TsEnterpriseSoftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseSoft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_SOFT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseSoft record);
}