package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterprise;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int insert(TsEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    List<TsEnterprise> selectByExample(TsEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    TsEnterprise selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterprise record, @Param("example") TsEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterprise record, @Param("example") TsEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterprise record);
}