package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseBatch;
import com.fly.twosoft.dao.twosoft.single.model.TsEnterpriseBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsEnterpriseBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int countByExample(TsEnterpriseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int deleteByExample(TsEnterpriseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int insert(TsEnterpriseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int insertSelective(TsEnterpriseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    List<TsEnterpriseBatch> selectByExample(TsEnterpriseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    TsEnterpriseBatch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsEnterpriseBatch record, @Param("example") TsEnterpriseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsEnterpriseBatch record, @Param("example") TsEnterpriseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsEnterpriseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ENTERPRISE_BATCH
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsEnterpriseBatch record);
}