package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsFile;
import com.fly.twosoft.dao.twosoft.single.model.TsFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int countByExample(TsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int deleteByExample(TsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int insert(TsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int insertSelective(TsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    List<TsFile> selectByExample(TsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    TsFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsFile record, @Param("example") TsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsFile record, @Param("example") TsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FILE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsFile record);
}