package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsNation;
import com.fly.twosoft.dao.twosoft.single.model.TsNationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsNationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int countByExample(TsNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int deleteByExample(TsNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int insert(TsNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int insertSelective(TsNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    List<TsNation> selectByExample(TsNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    TsNation selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsNation record, @Param("example") TsNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsNation record, @Param("example") TsNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_NATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsNation record);
}