package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsPrintRemark;
import com.fly.twosoft.dao.twosoft.single.model.TsPrintRemarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsPrintRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int countByExample(TsPrintRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int deleteByExample(TsPrintRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int insert(TsPrintRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int insertSelective(TsPrintRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    List<TsPrintRemark> selectByExample(TsPrintRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    TsPrintRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsPrintRemark record, @Param("example") TsPrintRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsPrintRemark record, @Param("example") TsPrintRemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsPrintRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsPrintRemark record);
}