package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsProduct;
import com.fly.twosoft.dao.twosoft.single.model.TsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int countByExample(TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int deleteByExample(TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int insert(TsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int insertSelective(TsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    List<TsProduct> selectByExampleWithBLOBs(TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    List<TsProduct> selectByExample(TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    TsProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsProduct record, @Param("example") TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TsProduct record, @Param("example") TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsProduct record, @Param("example") TsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsProduct record);
}