package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsProductHistory;
import com.fly.twosoft.dao.twosoft.single.model.TsProductHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsProductHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int insert(TsProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(TsProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    List<TsProductHistory> selectByExampleWithBLOBs(TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    List<TsProductHistory> selectByExample(TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    TsProductHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsProductHistory record, @Param("example") TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TsProductHistory record, @Param("example") TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsProductHistory record, @Param("example") TsProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TsProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsProductHistory record);
}