package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsProductBatch;
import com.fly.twosoft.dao.twosoft.single.model.TsProductBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsProductBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int countByExample(TsProductBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int deleteByExample(TsProductBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int insert(TsProductBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int insertSelective(TsProductBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    List<TsProductBatch> selectByExample(TsProductBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    TsProductBatch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsProductBatch record, @Param("example") TsProductBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsProductBatch record, @Param("example") TsProductBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsProductBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PRODUCT_BATCH
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsProductBatch record);
}