package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsShow;
import com.fly.twosoft.dao.twosoft.single.model.TsShowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int countByExample(TsShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int deleteByExample(TsShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int insert(TsShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int insertSelective(TsShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    List<TsShow> selectByExample(TsShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    TsShow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsShow record, @Param("example") TsShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsShow record, @Param("example") TsShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsShow record);
}