package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsShowOther;
import com.fly.twosoft.dao.twosoft.single.model.TsShowOtherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsShowOtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int countByExample(TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int deleteByExample(TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int insert(TsShowOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int insertSelective(TsShowOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    List<TsShowOther> selectByExampleWithBLOBs(TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    List<TsShowOther> selectByExample(TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    TsShowOther selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsShowOther record, @Param("example") TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TsShowOther record, @Param("example") TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsShowOther record, @Param("example") TsShowOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsShowOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TsShowOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SHOW_OTHER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsShowOther record);
}