package com.fly.twosoft.dao.twosoft.single.mapper;

import com.fly.twosoft.dao.twosoft.single.model.TsSite;
import com.fly.twosoft.dao.twosoft.single.model.TsSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int countByExample(TsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int deleteByExample(TsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int insert(TsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int insertSelective(TsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    List<TsSite> selectByExample(TsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    TsSite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TsSite record, @Param("example") TsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TsSite record, @Param("example") TsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsSite record);
}