package com.fly.twosoft.dao.twosoft.single.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;

public class TsDict implements Serializable {
    public static final String REF_TABLE_ALIAS_dict = "p";

    //
    private String dictKey;

    //
    private String dictName;

    //
    private String dictValue;

    //创建用户ID
    private String createPersonId;

    //创建用户名称
    private String createPersonName;

    //创建时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    //更新用户ID
    private String updatePersonId;

    //更新用户名称
    private String updatePersonName;

    //更新时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    //删除状态:1、正常; 2、已删除;
    private Short deleteState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_DICT
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getDictKey() {
        return dictKey;
    }

    //设置
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey == null ? null : dictKey.trim();
    }

    //返回
    public String getDictName() {
        return dictName;
    }

    //设置
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    //返回
    public String getDictValue() {
        return dictValue;
    }

    //设置
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    //返回创建用户ID
    public String getCreatePersonId() {
        return createPersonId;
    }

    //设置创建用户ID
    public void setCreatePersonId(String createPersonId) {
        this.createPersonId = createPersonId == null ? null : createPersonId.trim();
    }

    //返回创建用户名称
    public String getCreatePersonName() {
        return createPersonName;
    }

    //设置创建用户名称
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    //返回创建时间
    public Date getCreateTime() {
        return createTime;
    }

    //设置创建时间
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    //返回更新用户ID
    public String getUpdatePersonId() {
        return updatePersonId;
    }

    //设置更新用户ID
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId == null ? null : updatePersonId.trim();
    }

    //返回更新用户名称
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    //设置更新用户名称
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    //返回更新时间
    public Date getUpdateTime() {
        return updateTime;
    }

    //设置更新时间
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    //返回删除状态:1、正常; 2、已删除;
    public Short getDeleteState() {
        return deleteState;
    }

    //设置删除状态:1、正常; 2、已删除;
    public void setDeleteState(Short deleteState) {
        this.deleteState = deleteState;
    }
}