package com.fly.twosoft.dao.twosoft.single.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;

public class TsEnterprisePrint implements Serializable {
    public static final String REF_TABLE_ALIAS_enterprisePrint = "s";

    //
    private String id;

    //
    private String enterpriseId;

    //
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date printTime;

    //
    private Short printReason;

    //
    private String printContent;

    //
    private String printRemark;

    //
    private Short deleteState;

    //创建用户ID
    private String createPersonId;

    //创建用户名称
    private String createPersonName;

    //创建时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    //更新用户ID
    private String updatePersonId;

    //更新用户名称
    private String updatePersonName;

    //更新时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_PRINT
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getEnterpriseId() {
        return enterpriseId;
    }

    //设置
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    //返回
    public Date getPrintTime() {
        return printTime;
    }

    //设置
    public void setPrintTime(Date printTime) {
        this.printTime = printTime;
    }

    //返回
    public Short getPrintReason() {
        return printReason;
    }

    //设置
    public void setPrintReason(Short printReason) {
        this.printReason = printReason;
    }

    //返回
    public String getPrintContent() {
        return printContent;
    }

    //设置
    public void setPrintContent(String printContent) {
        this.printContent = printContent == null ? null : printContent.trim();
    }

    //返回
    public String getPrintRemark() {
        return printRemark;
    }

    //设置
    public void setPrintRemark(String printRemark) {
        this.printRemark = printRemark == null ? null : printRemark.trim();
    }

    //返回
    public Short getDeleteState() {
        return deleteState;
    }

    //设置
    public void setDeleteState(Short deleteState) {
        this.deleteState = deleteState;
    }

    //返回创建用户ID
    public String getCreatePersonId() {
        return createPersonId;
    }

    //设置创建用户ID
    public void setCreatePersonId(String createPersonId) {
        this.createPersonId = createPersonId == null ? null : createPersonId.trim();
    }

    //返回创建用户名称
    public String getCreatePersonName() {
        return createPersonName;
    }

    //设置创建用户名称
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    //返回创建时间
    public Date getCreateTime() {
        return createTime;
    }

    //设置创建时间
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    //返回更新用户ID
    public String getUpdatePersonId() {
        return updatePersonId;
    }

    //设置更新用户ID
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId == null ? null : updatePersonId.trim();
    }

    //返回更新用户名称
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    //设置更新用户名称
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    //返回更新时间
    public Date getUpdateTime() {
        return updateTime;
    }

    //设置更新时间
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}