package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseProductHistory implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseProductHistory = "ae";

    //
    private String id;

    //
    private String historyId;

    //
    private String name;

    //
    private String evaluateNo;

    //
    private String type;

    //
    private String area;

    //
    private Double money;

    //
    private Integer flyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_PRODUCT_HISTORY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getHistoryId() {
        return historyId;
    }

    //设置
    public void setHistoryId(String historyId) {
        this.historyId = historyId == null ? null : historyId.trim();
    }

    //返回
    public String getName() {
        return name;
    }

    //设置
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    //返回
    public String getEvaluateNo() {
        return evaluateNo;
    }

    //设置
    public void setEvaluateNo(String evaluateNo) {
        this.evaluateNo = evaluateNo == null ? null : evaluateNo.trim();
    }

    //返回
    public String getType() {
        return type;
    }

    //设置
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    //返回
    public String getArea() {
        return area;
    }

    //设置
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    //返回
    public Double getMoney() {
        return money;
    }

    //设置
    public void setMoney(Double money) {
        this.money = money;
    }

    //返回
    public Integer getFlyIndex() {
        return flyIndex;
    }

    //设置
    public void setFlyIndex(Integer flyIndex) {
        this.flyIndex = flyIndex;
    }
}