package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseHardware implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseHardware = "af";

    //
    private String id;

    //
    private String enterpriseId;

    //
    private Short type;

    //
    private String version;

    //
    private Integer num;

    //
    private Integer flyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_HARDWARE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getEnterpriseId() {
        return enterpriseId;
    }

    //设置
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    //返回
    public Short getType() {
        return type;
    }

    //设置
    public void setType(Short type) {
        this.type = type;
    }

    //返回
    public String getVersion() {
        return version;
    }

    //设置
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    //返回
    public Integer getNum() {
        return num;
    }

    //设置
    public void setNum(Integer num) {
        this.num = num;
    }

    //返回
    public Integer getFlyIndex() {
        return flyIndex;
    }

    //设置
    public void setFlyIndex(Integer flyIndex) {
        this.flyIndex = flyIndex;
    }
}