package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseKnowlegeHistory implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseKnowlegeHistory = "ac";

    //
    private String id;

    //
    private String historyId;

    //
    private String content;

    //
    private Integer flyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_KNOWLEGE_HISTORY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getHistoryId() {
        return historyId;
    }

    //设置
    public void setHistoryId(String historyId) {
        this.historyId = historyId == null ? null : historyId.trim();
    }

    //返回
    public String getContent() {
        return content;
    }

    //设置
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    //返回
    public Integer getFlyIndex() {
        return flyIndex;
    }

    //设置
    public void setFlyIndex(Integer flyIndex) {
        this.flyIndex = flyIndex;
    }
}