package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseStaffStock implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseStaffStock = "x";

    //
    private String id;

    //
    private String enterpriseId;

    //
    private Short type;

    //
    private Integer stockNum;

    //
    private Double stockPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_STAFF_STOCK
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getEnterpriseId() {
        return enterpriseId;
    }

    //设置
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    //返回
    public Short getType() {
        return type;
    }

    //设置
    public void setType(Short type) {
        this.type = type;
    }

    //返回
    public Integer getStockNum() {
        return stockNum;
    }

    //设置
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    //返回
    public Double getStockPercent() {
        return stockPercent;
    }

    //设置
    public void setStockPercent(Double stockPercent) {
        this.stockPercent = stockPercent;
    }
}