package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseSoftHistory implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseSoftHistory = "ai";

    //
    private String id;

    //
    private String historyId;

    //
    private Short type;

    //
    private String name;

    //
    private String softFrom;

    //
    private Integer softNum;

    //
    private String buyRent;

    //
    private Integer flyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_SOFT_HISTORY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getHistoryId() {
        return historyId;
    }

    //设置
    public void setHistoryId(String historyId) {
        this.historyId = historyId == null ? null : historyId.trim();
    }

    //返回
    public Short getType() {
        return type;
    }

    //设置
    public void setType(Short type) {
        this.type = type;
    }

    //返回
    public String getName() {
        return name;
    }

    //设置
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    //返回
    public String getSoftFrom() {
        return softFrom;
    }

    //设置
    public void setSoftFrom(String softFrom) {
        this.softFrom = softFrom == null ? null : softFrom.trim();
    }

    //返回
    public Integer getSoftNum() {
        return softNum;
    }

    //设置
    public void setSoftNum(Integer softNum) {
        this.softNum = softNum;
    }

    //返回
    public String getBuyRent() {
        return buyRent;
    }

    //设置
    public void setBuyRent(String buyRent) {
        this.buyRent = buyRent == null ? null : buyRent.trim();
    }

    //返回
    public Integer getFlyIndex() {
        return flyIndex;
    }

    //设置
    public void setFlyIndex(Integer flyIndex) {
        this.flyIndex = flyIndex;
    }
}