package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseShareholder implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseShareholder = "v";

    //
    private String id;

    //
    private String enterpriseId;

    //
    private String name;

    //
    private Integer stockNum;

    //
    private Double stockPercent;

    //
    private Integer flyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_SHAREHOLDER
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getEnterpriseId() {
        return enterpriseId;
    }

    //设置
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    //返回
    public String getName() {
        return name;
    }

    //设置
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    //返回
    public Integer getStockNum() {
        return stockNum;
    }

    //设置
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    //返回
    public Double getStockPercent() {
        return stockPercent;
    }

    //设置
    public void setStockPercent(Double stockPercent) {
        this.stockPercent = stockPercent;
    }

    //返回
    public Integer getFlyIndex() {
        return flyIndex;
    }

    //设置
    public void setFlyIndex(Integer flyIndex) {
        this.flyIndex = flyIndex;
    }
}