package com.fly.twosoft.dao.twosoft.single.model;

import java.io.Serializable;

public class TsEnterpriseBusiness implements Serializable {
    public static final String REF_TABLE_ALIAS_enterpriseBusiness = "z";

    //
    private String id;

    //
    private String enterpriseId;

    //
    private Short type;

    //
    private Double money;

    //
    private Double moneyPercent;

    //
    private Double selfMoney;

    //
    private Double selfPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ENTERPRISE_BUSINESS
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getEnterpriseId() {
        return enterpriseId;
    }

    //设置
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    //返回
    public Short getType() {
        return type;
    }

    //设置
    public void setType(Short type) {
        this.type = type;
    }

    //返回
    public Double getMoney() {
        return money;
    }

    //设置
    public void setMoney(Double money) {
        this.money = money;
    }

    //返回
    public Double getMoneyPercent() {
        return moneyPercent;
    }

    //设置
    public void setMoneyPercent(Double moneyPercent) {
        this.moneyPercent = moneyPercent;
    }

    //返回
    public Double getSelfMoney() {
        return selfMoney;
    }

    //设置
    public void setSelfMoney(Double selfMoney) {
        this.selfMoney = selfMoney;
    }

    //返回
    public Double getSelfPercent() {
        return selfPercent;
    }

    //设置
    public void setSelfPercent(Double selfPercent) {
        this.selfPercent = selfPercent;
    }
}