package com.fly.twosoft.dao.twosoft.single.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;

public class TsPrintRemark implements Serializable {
    public static final String REF_TABLE_ALIAS_printRemark = "t";

    //
    private String id;

    //
    private String orgId;

    //
    private String enterpriseRemark;

    //
    private String productRemark;

    //创建用户ID
    private String createPersonId;

    //创建用户名称
    private String createPersonName;

    //创建时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    //更新用户ID
    private String updatePersonId;

    //更新用户名称
    private String updatePersonName;

    //更新时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_PRINT_REMARK
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getOrgId() {
        return orgId;
    }

    //设置
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    //返回
    public String getEnterpriseRemark() {
        return enterpriseRemark;
    }

    //设置
    public void setEnterpriseRemark(String enterpriseRemark) {
        this.enterpriseRemark = enterpriseRemark == null ? null : enterpriseRemark.trim();
    }

    //返回
    public String getProductRemark() {
        return productRemark;
    }

    //设置
    public void setProductRemark(String productRemark) {
        this.productRemark = productRemark == null ? null : productRemark.trim();
    }

    //返回创建用户ID
    public String getCreatePersonId() {
        return createPersonId;
    }

    //设置创建用户ID
    public void setCreatePersonId(String createPersonId) {
        this.createPersonId = createPersonId == null ? null : createPersonId.trim();
    }

    //返回创建用户名称
    public String getCreatePersonName() {
        return createPersonName;
    }

    //设置创建用户名称
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    //返回创建时间
    public Date getCreateTime() {
        return createTime;
    }

    //设置创建时间
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    //返回更新用户ID
    public String getUpdatePersonId() {
        return updatePersonId;
    }

    //设置更新用户ID
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId == null ? null : updatePersonId.trim();
    }

    //返回更新用户名称
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    //设置更新用户名称
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    //返回更新时间
    public Date getUpdateTime() {
        return updateTime;
    }

    //设置更新时间
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}