package com.fly.twosoft.dao.twosoft.single.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;

public class TsProductVerify implements Serializable {
    public static final String REF_TABLE_ALIAS_productVerify = "r";

    //
    private String id;

    //
    private String productId;

    //
    private Short verifyState;

    //
    private String verifyResult;

    //
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date verifyTime;

    //
    private Short quickState;

    //
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date quickApplyTime;

    //
    private String quickRemark;

    //
    private String quickFileName;

    //创建用户ID
    private String createPersonId;

    //创建用户名称
    private String createPersonName;

    //创建时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    //更新用户ID
    private String updatePersonId;

    //更新用户名称
    private String updatePersonName;

    //更新时间
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_PRODUCT_VERIFY
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getProductId() {
        return productId;
    }

    //设置
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    //返回
    public Short getVerifyState() {
        return verifyState;
    }

    //设置
    public void setVerifyState(Short verifyState) {
        this.verifyState = verifyState;
    }

    //返回
    public String getVerifyResult() {
        return verifyResult;
    }

    //设置
    public void setVerifyResult(String verifyResult) {
        this.verifyResult = verifyResult == null ? null : verifyResult.trim();
    }

    //返回
    public Date getVerifyTime() {
        return verifyTime;
    }

    //设置
    public void setVerifyTime(Date verifyTime) {
        this.verifyTime = verifyTime;
    }

    //返回
    public Short getQuickState() {
        return quickState;
    }

    //设置
    public void setQuickState(Short quickState) {
        this.quickState = quickState;
    }

    //返回
    public Date getQuickApplyTime() {
        return quickApplyTime;
    }

    //设置
    public void setQuickApplyTime(Date quickApplyTime) {
        this.quickApplyTime = quickApplyTime;
    }

    //返回
    public String getQuickRemark() {
        return quickRemark;
    }

    //设置
    public void setQuickRemark(String quickRemark) {
        this.quickRemark = quickRemark == null ? null : quickRemark.trim();
    }

    //返回
    public String getQuickFileName() {
        return quickFileName;
    }

    //设置
    public void setQuickFileName(String quickFileName) {
        this.quickFileName = quickFileName == null ? null : quickFileName.trim();
    }

    //返回创建用户ID
    public String getCreatePersonId() {
        return createPersonId;
    }

    //设置创建用户ID
    public void setCreatePersonId(String createPersonId) {
        this.createPersonId = createPersonId == null ? null : createPersonId.trim();
    }

    //返回创建用户名称
    public String getCreatePersonName() {
        return createPersonName;
    }

    //设置创建用户名称
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    //返回创建时间
    public Date getCreateTime() {
        return createTime;
    }

    //设置创建时间
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    //返回更新用户ID
    public String getUpdatePersonId() {
        return updatePersonId;
    }

    //设置更新用户ID
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId == null ? null : updatePersonId.trim();
    }

    //返回更新用户名称
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    //设置更新用户名称
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    //返回更新时间
    public Date getUpdateTime() {
        return updateTime;
    }

    //设置更新时间
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}