package com.fly.twosoft.dao.twosoft.single.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;

public class TsSite implements Serializable {
    public static final String REF_TABLE_ALIAS_site = "n";

    //
    private String id;

    //
    private String name;

    //
    private String link;

    //
    private Integer siteIndex;

    //
    private String logoFileName;

    //
    private String logoFilePath;

    //
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date showTime;

    //
    private Short showState;

    //
    private Short deleteState;

    //
    private String createPersonId;

    //
    private String createPersonName;

    //
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    //
    private String updatePersonId;

    //
    private String updatePersonName;

    //
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_SITE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    //返回
    public String getId() {
        return id;
    }

    //设置
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    //返回
    public String getName() {
        return name;
    }

    //设置
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    //返回
    public String getLink() {
        return link;
    }

    //设置
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    //返回
    public Integer getSiteIndex() {
        return siteIndex;
    }

    //设置
    public void setSiteIndex(Integer siteIndex) {
        this.siteIndex = siteIndex;
    }

    //返回
    public String getLogoFileName() {
        return logoFileName;
    }

    //设置
    public void setLogoFileName(String logoFileName) {
        this.logoFileName = logoFileName == null ? null : logoFileName.trim();
    }

    //返回
    public String getLogoFilePath() {
        return logoFilePath;
    }

    //设置
    public void setLogoFilePath(String logoFilePath) {
        this.logoFilePath = logoFilePath == null ? null : logoFilePath.trim();
    }

    //返回
    public Date getShowTime() {
        return showTime;
    }

    //设置
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    //返回
    public Short getShowState() {
        return showState;
    }

    //设置
    public void setShowState(Short showState) {
        this.showState = showState;
    }

    //返回
    public Short getDeleteState() {
        return deleteState;
    }

    //设置
    public void setDeleteState(Short deleteState) {
        this.deleteState = deleteState;
    }

    //返回
    public String getCreatePersonId() {
        return createPersonId;
    }

    //设置
    public void setCreatePersonId(String createPersonId) {
        this.createPersonId = createPersonId == null ? null : createPersonId.trim();
    }

    //返回
    public String getCreatePersonName() {
        return createPersonName;
    }

    //设置
    public void setCreatePersonName(String createPersonName) {
        this.createPersonName = createPersonName == null ? null : createPersonName.trim();
    }

    //返回
    public Date getCreateTime() {
        return createTime;
    }

    //设置
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    //返回
    public String getUpdatePersonId() {
        return updatePersonId;
    }

    //设置
    public void setUpdatePersonId(String updatePersonId) {
        this.updatePersonId = updatePersonId == null ? null : updatePersonId.trim();
    }

    //返回
    public String getUpdatePersonName() {
        return updatePersonName;
    }

    //设置
    public void setUpdatePersonName(String updatePersonName) {
        this.updatePersonName = updatePersonName == null ? null : updatePersonName.trim();
    }

    //返回
    public Date getUpdateTime() {
        return updateTime;
    }

    //设置
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}